"""Document download/generation tools for Dolibarr MCP Server."""

from fastmcp import FastMCP
from pydantic import Field

from ..dolibarr_client import DolibarrClient
from ..models import DocumentDownloadResult


def _require_client() -> DolibarrClient:
    """Ensure client is initialized and return it."""
    from ..state import get_client
    return get_client()


def register_document_tools(mcp: FastMCP) -> None:
    """Register document download/generation tools with the MCP server."""

    @mcp.tool()
    async def download_document(
        modulepart: str = Field(..., description="Dolibarr module part, e.g. 'propal', 'facture', 'order', 'contrat'"),
        original_file: str = Field(..., description="Relative file path within the module's document dir, e.g. 'PR2601-0001/PR2601-0001.odt'")
    ) -> DocumentDownloadResult:
        """Download a document already generated by Dolibarr.

        The file must already exist on the Dolibarr server. Returns the file
        content base64-encoded (see DocumentDownloadResult.content/encoding).
        """
        client = _require_client()
        result = await client.download_document(modulepart, original_file)
        return DocumentDownloadResult(**result)

    @mcp.tool()
    async def download_proposal_document(
        proposal_id: int = Field(..., description="Proposal ID")
    ) -> DocumentDownloadResult:
        """Download the generated document (e.g. ODT/PDF) for a proposal.

        Looks up the proposal's last generated document (last_main_doc) and
        downloads it. Raises an error if no document has been generated yet
        for this proposal — generate one first with build_proposal_document.
        """
        client = _require_client()
        proposal = await client.get_proposal_by_id(proposal_id)
        original_file = proposal.get("last_main_doc")
        if not original_file:
            raise ValueError(
                f"Proposal {proposal_id} has no generated document yet (last_main_doc empty). "
                "Generate one first with build_proposal_document."
            )
        result = await client.download_document("propal", original_file)
        return DocumentDownloadResult(**result)

    @mcp.tool()
    async def build_proposal_document(
        proposal_id: int = Field(..., description="Proposal ID"),
        doctemplate: str = Field("", description="ODT/PDF template name (defaults to the proposal's configured template)"),
        langcode: str = Field("", description="Language code, e.g. 'de_DE' (defaults to system language)")
    ) -> DocumentDownloadResult:
        """(Re)generate the document for a proposal on the Dolibarr server.

        Use this to create the document before download_proposal_document,
        or to refresh it after changes to the proposal.
        """
        client = _require_client()
        proposal = await client.get_proposal_by_id(proposal_id)
        ref = proposal.get("ref")
        if not ref:
            raise ValueError(f"Proposal {proposal_id} has no ref; cannot build document")
        original_file = proposal.get("last_main_doc") or f"{ref}/{ref}.pdf"
        result = await client.build_document("propal", original_file, doctemplate=doctemplate, langcode=langcode)
        return DocumentDownloadResult(**result)
